dino:
  head_n_prototypes: 65536
  head_bottleneck_dim: 256
ibot:
  separate_head: true
  head_n_prototypes: 65536
train:
  batch_size_per_gpu: 32
  dataset_path: RecursiveImageDataset:root=~/.datasets
  centering: sinkhorn_knopp
student:
  arch: vit_base
  patch_size: 14
  drop_path_rate: 0.4 # Usually 0.4
  ffn_layer: swiglufused
  block_chunks: 4
teacher:
  momentum_teacher: 0.994
optim:
  epochs: 100
  weight_decay_end: 0.2
  base_lr: 2.0e-04  # learning rate for a batch size of 1024. Autoscaling is applied for smaller batches sizes in dinov2/utils/config.py
  warmup_epochs: 10
  layerwise_decay: 1.0
crops:
  local_crops_size: 98